Added a warning when signal is loaded and comes up empty for easier debugging.
LBHB/NEMS0 pull request #68
Opened 2018-04-17 23:30 UTC by lshaheen

Side note: Python seems to stop executing when it encounters a RuntimeWarning. Is there some setting that I can change to make it keep going?

2018-04-17 23:40 UTC, jacobpennington commented
Looks like it's an issue with how I've been adding warnings (and maybe others have as well?) Instead of `raise RuntimeWarning('blah blah')` we should be using `import warnings` `warnings.warn('blah blah', RuntimeWarning). Doing it with raise causes it to be treated as an exception, which is why it's stopping execution. https://docs.python.org/3/library/warnings.html#warnings.warn

2018-04-17 23:41 UTC, jacobpennington requested changes
See comment regarding warnings module.

2018-04-18 20:22 UTC, lshaheen commented
Fixed.

2018-04-18 20:24 UTC, jacobpennington approved these changes

2018-04-18 20:25 UTC, merged